
services:
  postgres:
    image: postgres:17
    container_name: db
    ports:
      - "${DB_PORT}:${DB_PORT}"
    restart: unless-stopped
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    env_file:
      - ./todo-service/.env
  todo-service:
    build:
      context: .
      dockerfile: ./todo-service/Dockerfile
    container_name: todo-service
    ports:
      - "${TODO_PORT}:${TODO_PORT}"
    env_file:
      - ./todo-service/.env
    depends_on:
      - postgres
      - auth-service
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    env_file:
      - ./auth-service/.env
