// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HashReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashReq) Reset() {
	*x = HashReq{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashReq) ProtoMessage() {}

func (x *HashReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashReq.ProtoReflect.Descriptor instead.
func (*HashReq) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

func (x *HashReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type HashRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashRes) Reset() {
	*x = HashRes{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashRes) ProtoMessage() {}

func (x *HashRes) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashRes.ProtoReflect.Descriptor instead.
func (*HashRes) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

func (x *HashRes) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type JWTReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JWTReq) Reset() {
	*x = JWTReq{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JWTReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWTReq) ProtoMessage() {}

func (x *JWTReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWTReq.ProtoReflect.Descriptor instead.
func (*JWTReq) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{2}
}

func (x *JWTReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type JWTRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JWTRes) Reset() {
	*x = JWTRes{}
	mi := &file_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JWTRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWTRes) ProtoMessage() {}

func (x *JWTRes) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWTRes.ProtoReflect.Descriptor instead.
func (*JWTRes) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{3}
}

func (x *JWTRes) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CompareReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareReq) Reset() {
	*x = CompareReq{}
	mi := &file_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareReq) ProtoMessage() {}

func (x *CompareReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareReq.ProtoReflect.Descriptor instead.
func (*CompareReq) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{4}
}

func (x *CompareReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CompareReq) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type CompareRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Compare       bool                   `protobuf:"varint,1,opt,name=compare,proto3" json:"compare,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareRes) Reset() {
	*x = CompareRes{}
	mi := &file_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareRes) ProtoMessage() {}

func (x *CompareRes) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareRes.ProtoReflect.Descriptor instead.
func (*CompareRes) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{5}
}

func (x *CompareRes) GetCompare() bool {
	if x != nil {
		return x.Compare
	}
	return false
}

type ExtReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtReq) Reset() {
	*x = ExtReq{}
	mi := &file_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtReq) ProtoMessage() {}

func (x *ExtReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtReq.ProtoReflect.Descriptor instead.
func (*ExtReq) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{6}
}

func (x *ExtReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ExtRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtRes) Reset() {
	*x = ExtRes{}
	mi := &file_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtRes) ProtoMessage() {}

func (x *ExtRes) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtRes.ProtoReflect.Descriptor instead.
func (*ExtRes) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{7}
}

func (x *ExtRes) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\x04auth\"%\n" +
	"\aHashReq\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\"\x1d\n" +
	"\aHashRes\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\" \n" +
	"\x06JWTReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\"\x1e\n" +
	"\x06JWTRes\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"<\n" +
	"\n" +
	"CompareReq\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\"&\n" +
	"\n" +
	"CompareRes\x12\x18\n" +
	"\acompare\x18\x01 \x01(\bR\acompare\"\x1e\n" +
	"\x06ExtReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\" \n" +
	"\x06ExtRes\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID2\xb5\x01\n" +
	"\vAuthService\x12&\n" +
	"\x06HashPd\x12\r.auth.HashReq\x1a\r.auth.HashRes\x12$\n" +
	"\x06GenJWT\x12\f.auth.JWTReq\x1a\f.auth.JWTRes\x12/\n" +
	"\tComparePd\x12\x10.auth.CompareReq\x1a\x10.auth.CompareRes\x12'\n" +
	"\tExtUserID\x12\f.auth.ExtReq\x1a\f.auth.ExtResB\x16Z\x14auth-service/pb;authb\x06proto3"

var (
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData []byte
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)))
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_auth_proto_goTypes = []any{
	(*HashReq)(nil),    // 0: auth.HashReq
	(*HashRes)(nil),    // 1: auth.HashRes
	(*JWTReq)(nil),     // 2: auth.JWTReq
	(*JWTRes)(nil),     // 3: auth.JWTRes
	(*CompareReq)(nil), // 4: auth.CompareReq
	(*CompareRes)(nil), // 5: auth.CompareRes
	(*ExtReq)(nil),     // 6: auth.ExtReq
	(*ExtRes)(nil),     // 7: auth.ExtRes
}
var file_auth_proto_depIdxs = []int32{
	0, // 0: auth.AuthService.HashPd:input_type -> auth.HashReq
	2, // 1: auth.AuthService.GenJWT:input_type -> auth.JWTReq
	4, // 2: auth.AuthService.ComparePd:input_type -> auth.CompareReq
	6, // 3: auth.AuthService.ExtUserID:input_type -> auth.ExtReq
	1, // 4: auth.AuthService.HashPd:output_type -> auth.HashRes
	3, // 5: auth.AuthService.GenJWT:output_type -> auth.JWTRes
	5, // 6: auth.AuthService.ComparePd:output_type -> auth.CompareRes
	7, // 7: auth.AuthService.ExtUserID:output_type -> auth.ExtRes
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
